### ISSUE TITLE
add a configuration to control whether display description for tree item

### ISSUE THREAD

**Issue by Latria-Kure** [tommyme/vscode-bookmark-x#22]
When using line text as the description of tree item, item will become too long. The width of treeview is depended on the longest tree item, so I have to drag the horizontal scrollbar all the way to the right to click the inline button of item every time. I try to achieve this feature, but I faced two problems:

1. After hiding the description, it's hard to distinguish between group and groupbookmark.
2. It's hard to access `WsfTreeItem.description`. If I want to modify it, I have to change the constructor or access it after it is consctructed in the `getChildren` of dataprovider.

Could you give me some advice?

**Comment by tommyme** [comment]
I don't get you, In my case, it's width can be adjust by dragging the view container.
How can "the width of treeview is depended on the longest tree item" happen?
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/be35dd13-dd5c-443a-8fba-865879505321">

**Comment by Latria-Kure** [comment]
Of course the width can be adjusted. But this means I have to resize the container every time if I want to click the inline button,  unless I always keep the container very wide. This will takes up too much space.

**Comment by tommyme** [comment]
Why do it need to adjust the width every time? Once I get the suitable width, the view will always be displayed at this width.
I don't understand why you need to keep the container very wide to click the inline button, can you please give me a picture of pdf to explain?

**Comment by Latria-Kure** [comment]
This is the case. The suitable width which allowing click the button will take up 1/3 screen space.
![case](https://github.com/user-attachments/assets/1f892590-35d4-4a3c-afa4-4a09f4008fd9)

Hiding the description can reduce the space occupied by the view container to 1/7.
![image](https://github.com/user-attachments/assets/848a31ff-deb0-4b8b-b2f9-8f663b907c0c)

**Comment by Latria-Kure** [comment]
Yes, you are right! A new empty profile work. I will find the reason.
![image](https://github.com/user-attachments/assets/e8475513-3709-49b0-9e58-38e19c354556)

**Comment by Latria-Kure** [comment]
I figured it out! Set `workbench.list.horizontalScrolling` to `false` will solve it. Thank you very much! BookmarkX is perfect now!
