### ISSUE TITLE
[bmx] [feat] Bookmarks misplaced after code modification

### ISSUE THREAD

**Issue by zhourrr** [tommyme/vscode-bookmark-x#27]
Hello, I'd like to thank you for this wonderful plugin. It has been incredibly useful in my development workflow.

I'm aware that bookmarks might be misplaced after code modification or git pull, and sometimes this is impossible to resolve automatically. But most of the time the bookmarks are only a few lines away from their intended positions. In such cases, I can manually remove the old bookmark and add a new one that points to the correct position. But this process of removing and then adding is a bit tedious, especially when there are multiple bookmarks to reset.

I was wondering how you guys cope with this? Is there some existing features to improve experience? Say a command to move a bookmark down or up a line? Thank you!

**Comment by tommyme** [comment]
First of all, thank you for your love and support for bmx.

> I'm aware that bookmarks might be misplaced after code modification or git pull, and sometimes this is impossible to resolve automatically.

Yes, It's very diffcult to track git actions for bookmark plugins.

> But most of the time the bookmarks are only a few lines away from their intended positions. In such cases, I can manually remove the old bookmark and add a new one that points to the correct position. But this process of removing and then adding is a bit tedious, especially when there are multiple bookmarks to reset.

It's important to have the ability to modify the bookmarks affected by git pull. **I'll think of a solution later and you can share your idea with us.**

> I was wondering how you guys cope with this? Is there some existing features to improve experience? Say a command to move a bookmark down or up a line? Thank you!

For my use case, bookmarks are used to understand a repo or a system. I don't bookmark modules/files that change frequently. In fact, I am deliberately avoiding the defects of bookmark plugins.

**Comment by tommyme** [comment]
For now, you can try to do the following step to make it less tedious.
1. save bookmarks to json using command `save state of all workspace`
2. backup the bookmark json file.
3. edit bookmark in bookmark json, you can edit line number directly.
4. load bookmarks json to make modification work.

**Comment by zhourrr** [comment]
> For now, you can try to do the following step to make it less tedious.
> 
> 1. save bookmarks to json using command `save state of all workspace`
> 2. backup the bookmark json file.
> 3. edit bookmark in bookmark json, you can edit line number directly.
> 4. load bookmarks json to make modification work.

Thank you, this works. It would also be very handy if there is a command similar to "Alt+Up Arrow" or "Alt+Down Arrow" to move a bookmark. This way, I could easily move a bookmark pinned at line 10 to line 9, for instance.

**Comment by tommyme** [comment]
Look good to me and easy to realize, I'll notify you once I've done.

**Comment by tommyme** [comment]
there is a command `>toggle label bookmark force` which can make your work easier

this command can make a bookmark to overwrite the bookmark with same name

**Comment by tommyme** [comment]
Work in process #29

**Comment by zhourrr** [comment]
> Work in process #29

Thanks!

I've noticed another issue:  after some bookmarks were misplaced, when I run the "reveal bookmark in current line" command on those misplaced bookmarks, Bookmark X hangs for several minutes and eventually restarts.

I suspect this happens because the "line text" and "line number" do not match any records in the bookmark's state. It would be helpful if Bookmark X could return a message saying "Current bookmark not found." and exit the searching loop.

**Comment by tommyme** [comment]
This is an important bug, thanks alot, I'll fix it soon.

**Comment by tommyme** [comment]
> This is an important bug, thanks alot, I'll fix it soon.

I can't reproduce this error, could you give me an example?

**Comment by tommyme** [comment]
the feat is implemented in #29 and #32. the beta version plugin will be published later.😊
