### ISSUE TITLE
Freely arrange bookmarks in the tree

### ISSUE THREAD

**Issue by aratar-orome** [tommyme/vscode-bookmark-x#5]
Hi,

It would be very helpful to be able to arrange created bookmarks in an arbitrary order. I would like to sort bookmarks according the logical flow in the software.

Thanks in advance,

Aratar Orome

**Comment by tommyme** [comment]
that feature is very good, but currently It's hard to add it, because vscode tree view currently can only handle "drop on a node", can't handle "drop before/after a node".

Although this requirement can be achieved using some magical methods, it would complicate the code and affect many related functionalities. 

Currently, the bookmarks order can be controlled by using bookmark commands, such as `000-someFunc` and `010-innerFunc`.

**Comment by aratar-orome** [comment]
Thank you for thinking about it. But what do you mean the bookmarks oder can be controlled by someFunc?

**Comment by tommyme** [comment]
bookmarks are sorted by name, like this:
<img width="243" alt="image" src="https://github.com/user-attachments/assets/d62c1cfd-5c05-4eea-961f-bfa0337eda1e">

**Comment by aratar-orome** [comment]
Ah, okay. Thank you for the explanation. For the meanwhile I will try it so, but for the future it would be great to have my wished feature as  no other bookmarks extension has implemented it. It would be a unique feature of bookmark x 😁. Of course I have understood your points.

**Comment by tommyme** [comment]
thank you for using bookmark x and helping me make it better, PRs are welcomed☺️

**Comment by tommyme** [comment]
you can have a try in beta version plugin, it add a new feature which allows you to freely arrange bookmarks in the tree.

To do that, you need to configure `bookmarkX.sort` to `manual` in settings

**Comment by aratar-orome** [comment]
It is fantastic that you have implemented that feature. Unfortunatly, I get an error "that situation not supported yet" when I move a bookmark in the tree.

**Comment by tommyme** [comment]
- are you using beta version of bookmark x ?
- if that happens in beta version, please give me a screenshot or gif to record the problem.

**Comment by aratar-orome** [comment]
I have the version 0.2.11. Is this the beta version?

**Comment by tommyme** [comment]
> I have the version 0.2.11. Is this the beta version?

yes
