### ISSUE TITLE
I want to implement another feature, need help

### ISSUE THREAD

**Issue by DragosStefanNecula** [tommyme/vscode-bookmark-x#8]
Hey! I hope you are well!

I want to implement a quick navigate feature, that shows you a menu like the quick activate feature does, but its full of bookmarks, and once you select a bookmark, you travel to it. However, I cant find the function that handles going to the bookmark. Would you please help me?

Thanks for reading, I hope you have a nice day.

**Comment by tommyme** [comment]
jump to bookmark use command `bookmark_x.jumpToBookmark`, when you click on the bookmark, It'll trigger this command and call `(bm: Bookmark) => controller.jumpToBookmark(bm)`

**Comment by tommyme** [comment]
Looking forward to your new features~

**Comment by tommyme** [comment]
you can install beta version plugin(0.2.10) to check the behaviour of new command.

**Comment by DragosStefanNecula** [comment]
Oh okay, thank you!

**Comment by DragosStefanNecula** [comment]
I want to implement another one that gets all the bookmarks from the active group. however there is no .cache on the active group, do you have a command to do that easily? or any ideas?

Please let me implement this one because I need the experience. :D

**Comment by DragosStefanNecula** [comment]
One way to do it is just to navigate through the children of the active group to generate that list of lines I can select from

**Comment by DragosStefanNecula** [comment]
I found the command "bfs_get_nodes()" I will use that
